app = "ana2-new"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8078"

[http_service]
  internal_port = 8078
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
